#!/usr/bin/env bash
# configures a ufw firewall to block all incoming traffic

sudo ufw default deny incoming
sudo ufw default allow outgoing
# allow incoming ssh traffic
sudo ufw allow 22/tcp

# allow incoming https (ssl) traffic
sudo ufw allow 443/tcp

# allow incoming http traffic
sudo ufw allow 80/tcp

# enable ufw to apply the rules
sudo ufw enable
